name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build

      - name: Clean old .next directory on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 49.232.8.45
          username: root
          password: Web198743@
          script: |
            rm -rf /root/next-app/.next
            mkdir -p /root/next-app

      - name: Upload `.next` to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 49.232.8.45
          username: root
          password: Web198743@
          source: ".next"
          target: "/root/next-app"

      - name: Upload server.js file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 49.232.8.45
          username: root
          password: Web198743@
          source: "server.js"
          target: "/root/next-app"

      - name: Upload package.json files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 49.232.8.45
          username: root
          password: Web198743@
          source: "package.json,pnpm-lock.yaml"
          target: "/root/next-app"

      - name: Upload PM2 config
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 49.232.8.45
          username: root
          password: Web198743@
          source: "pm2.config.cjs"
          target: "/root/next-app"

      - name: SSH install dependencies
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 49.232.8.45
          username: root
          password: Web198743@
          script: |
            cd /root/next-app
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            pnpm install --prod
            echo "=== 部署完成 ==="
            echo "请在服务器上运行: cd /root/next-app && pm2 start pm2.config.cjs"
